update the readme with api info
holepunchto/cmake-app-image pull request #1
Opened 2024-04-17 10:10 UTC by heyitsvi

2024-04-17 10:11 UTC, heyitsvi commented
just have a look to see if the cmake options look okay

2024-04-18 07:09 UTC, kasperisager requested changes

2024-04-18 07:09 UTC, kasperisager commented on README.md
> +Downloads the essential AppRun runtime component, required for executing AppImages.
```suggestion
#### `download_app_image_run`
Downloads the AppRun runtime component, required for executing AppImages.
```

2024-04-18 07:09 UTC, kasperisager commented on README.md
> +The desired location to save the downloaded AppRun file.
```suggestion
##### `DESTINATION <path>`
The desired location to save the downloaded AppRun file.
```

2024-04-18 07:09 UTC, kasperisager commented on README.md
> +CMake targets the AppImage build depends on.
````suggestion
#### `download_app_image_tool`
Fetches the AppImageTool utility, used to create and package AppImages.

##### `DESTINATION <path>`
The directory where the appimagetool file will be saved.

#### `add_app_image`
The core function to define and generate an AppImage for the application.

```cmake
add_app_image(
  <target> 
  [DESTINATION <path>] 
  NAME <string> 
  DESCRIPTION <string> 
  [ICON <path>] 
  [CATEGORY <string>]
  [TARGET <target>]
  [EXECUTABLE <path>]
  [APP_DIR <path>]
  [RESOURCES [FILE|DIR <from> <to>]... ]
  [DEPENDS <target...>]
)
```

##### `<target>` 
The name of the CMake target to create.

##### `DESTINATION <path>`
The output path for the generated AppImage file. Defaults to `"${NAME}.AppImage".

##### `NAME <string>`
The name of the application.

##### `DESCRIPTION <string>`
A short description of the application.

##### `ICON <path>`
Path to the application icon file.

##### `CATEGORY <string>`
The category for the app in Linux application menus.

##### `TARGET <target>`
An existing CMake target to execute as the main application entry point.

##### `EXECUTABLE <path>`
The direct path to the executable file. Use if not using the `TARGET` option.

##### `APP_DIR <path>`
The base directory to use for the AppImage contents. Defaults to `"${NAME}.AppDir"`.

##### `RESOURCES [FILE|DIR <from> <to>]...`
Additional files or directories to include in the AppImage.

###### `FILE <from> <to>`
Copies a single file from `<from>` to `<to>` inside the AppImage.

###### `DIR <from> <to>`
Copies an entire directory from `<from>` to `<to>` inside the AppImage.

##### `DEPENDS <target...>`
CMake targets the AppImage build depends on.
````

2024-04-18 07:22 UTC, merged